### ISSUE TITLE
unable to import bvh 

### ISSUE THREAD

**Issue by jonwong666** [jhoolmans/mayaImporterBVH#8]
hi there, I'm trying to import bvh from mocap software TPD ( https://digital-standard.booth.pm/items/5294636)

getting this error 

# Error: RuntimeError: file C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\pymel\internal\pmcmds.py line 130: Only one transform or joint can be selected for creation # 

I create a humanIK skeleton and select the hips joint. then press import.

**Comment by DonnieAlex** [comment]
maya 2020 runs on python 2, and this is clearly stated as the python 3 branch.
